### ISSUE TITLE
Feature: Backend transfer

### ISSUE THREAD

**Issue by adambaumeister** [adambaumeister/goflow#11]
Provide functionality for users to be able to direct, or archive, flow data to different backends based on time.

Example:

```yaml
transfer:
   - source: mysql
     destination: timescaledb
     older_than: 30
  
  - source: timescaledb
    destination: somewhereelse
    older_than: 180
```
